/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as TabsWorkoutRouteImport } from './routes/_tabs.workout'
import { Route as TabsProgressRouteImport } from './routes/_tabs.progress'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsCoachRouteImport } from './routes/_tabs.coach'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsWorkoutRoute = TabsWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProgressRoute = TabsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TabsRoute,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCoachRoute = TabsCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/coach': typeof TabsCoachRoute
  '/profile': typeof TabsProfileRoute
  '/progress': typeof TabsProgressRoute
  '/workout': typeof TabsWorkoutRoute
}
export interface FileRoutesByTo {
  '/coach': typeof TabsCoachRoute
  '/profile': typeof TabsProfileRoute
  '/progress': typeof TabsProgressRoute
  '/workout': typeof TabsWorkoutRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/coach': typeof TabsCoachRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/_tabs/progress': typeof TabsProgressRoute
  '/_tabs/workout': typeof TabsWorkoutRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coach' | '/profile' | '/progress' | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/coach' | '/profile' | '/progress' | '/workout' | '/'
  id:
    | '__root__'
    | '/_tabs'
    | '/_tabs/coach'
    | '/_tabs/profile'
    | '/_tabs/progress'
    | '/_tabs/workout'
    | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/workout': {
      id: '/_tabs/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof TabsWorkoutRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/progress': {
      id: '/_tabs/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof TabsProgressRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/coach': {
      id: '/_tabs/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof TabsCoachRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsCoachRoute: typeof TabsCoachRoute
  TabsProfileRoute: typeof TabsProfileRoute
  TabsProgressRoute: typeof TabsProgressRoute
  TabsWorkoutRoute: typeof TabsWorkoutRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsCoachRoute: TabsCoachRoute,
  TabsProfileRoute: TabsProfileRoute,
  TabsProgressRoute: TabsProgressRoute,
  TabsWorkoutRoute: TabsWorkoutRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
